about/urls.py
from django.urls import path
from .views import about_view

app_name = 'about'

urlpatterns = [
    path('', about_view,  name='about_view')

 ]

blog/urls.py
from django.urls import path, include
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(),  name='post_list_view'),
    path('<slug:posts_slug>/', views.PostDetailView.as_view(), name='single_post_view'),
 ]

contact/urls.py
from django.urls import path
from .views import contact_view

app_name = 'contact'

urlpatterns = [
    path('', contact_view, name='contact_view')

 ]

main_page/urls.py
from django.urls import path
from .views import main_page_view

app_name = 'main_page'

urlpatterns = [
    path('', main_page_view, name='main_page_view')

 ]

psychology_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('about/', include('about.urls', namespace='about')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('contact/', include('contact.urls', namespace='contact'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models
from os import path
from uuid import uuid4

class Gallery(models.Model):

    def get_file_name(self, filename: str):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join('images/gallery', filename)

    photo = models.ImageField(upload_to=get_file_name)
    desc = models.CharField(max_length=100, blank=True)
    facebook = models.URLField()
    instagram = models.URLField()
    telegram = models.URLField()

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галерея'

blog/models.py
from django.db import models
from mptt.models import MPTTModel
from uuid import uuid4
from os import path
from django.urls import reverse



class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя тега')
    slug = models.SlugField(max_length=100)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class Posts(models.Model):
    def get_file_name(self, filename: str):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join('images/articles', filename)


    title = models.CharField(max_length=200, verbose_name='Название поста')
    photo = models.ImageField(upload_to=get_file_name, verbose_name='Фото')
    text = models.TextField(verbose_name='Текст поста')
    slug = models.SlugField(max_length=200)
    tags = models.ManyToManyField(Tag, related_name='post', verbose_name='Тег поста', blank=True)
    create_at = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    class MPTTMeta:
        order_insertion_by = ['title']


    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('blog:single_post_view', args=(self.slug,))

# class Exercises(models.Model):
#     name = models.CharField(max_length=100, verbose_name='Название упражнения')
#     prep_time = models.PositiveIntegerField(default=0, verbose_name='Сколько оно выполняеться по времени')
#     exercise = models.TextField(verbose_name='Описание упражнения')
#     post = models.ForeignKey(Post, related_name='exercises', on_delete=models.SET_NULL, null=True, blank=True)

contact/models.py
from django.db import models

class Contact(models.Model):
    telegram = models.URLField()
    facebook = models.URLField()
    instagram = models.URLField()
    title = models.CharField(max_length=50, verbose_name='Название секции', blank=True)
    desc = models.CharField(max_length=200, verbose_name='Описание', blank=True)
    address = models.CharField(max_length=100, verbose_name='Адрес', blank=True)
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона', blank=True)

main_page/models.py
from django.db import models
from uuid import uuid4
from os import path


class Main_page_model(models.Model):

    def get_file_name(self, filename: str):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join('images/main_page', filename)

    photo = models.ImageField(upload_to=get_file_name, verbose_name='Фото')
    title = models.CharField(max_length=50)
    desc = models.CharField(max_length=100)
    instagram = models.URLField()
    facebook = models.URLField()

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Главная страница'
        verbose_name_plural = 'Главная страница'

about/views.py
from django.shortcuts import render
from .models import Gallery

def about_view(request):
    gallery = Gallery.objects.all()
    return render(request, 'about/about.html', context={
        'gallery': gallery
    })

blog/views.py
from django.shortcuts import render
from .models import Posts, Tag
from django.views.generic import DetailView, ListView

class PostDetailView(DetailView):
    model = Posts
    context_object_name = "posts"
    slug_url_kwarg = 'posts_slug'
    template_name = 'blog/post_detail.html'

class PostListView(ListView):
    model = Posts
    paginate_by = 9
    template_name = "blog/posts_list.html"

contact/views.py
from django.shortcuts import render

def contact_view(request):
    return render(request, 'contact/contact.html', )

main_page/views.py
from django.shortcuts import render
from .models import Main_page_model

def main_page_view(request):
    main_page = Main_page_model.objects.all()
    return render(request, 'main_page/index.html', context={
        'main_page': main_page
    })

templates/blog/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Portfolio - Kelly Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Kelly - v4.8.1
  * Template URL: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">

      <h1 class="logo me-auto me-lg-0"><a href= {% url 'main_page:main_page_view' %} >Kelly</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a href={% url 'main_page:main_page_view' %}>Home</a></li>
          <li><a href="{% url 'about:about_view' %}">About</a></li>
          <li><a href="resume.html">Resume</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a class="active"  href="{% url 'blog:post_list_view' %}">Blog</a></li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <div class="header-social-links">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
      </div>

    </div>

  </header><!-- End Header -->

  <main id="main">

    <!-- Single Post Section Begin -->
    <section class="single-post spad">
        <div class="single-post__hero">
            <img src={{ posts.photo.url }} class="single-post__hero" alt="">
        </div>
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="single-post__title">
                        <div class="single-post__title__text">
                            <h4>{{ posts.title }}</h4>
                        </div>
                    </div>
                    <div class="single-post__middle__text">
                        <p>{{ posts.text|safe }}</p>
                    </div>
                    <div class="single-post__tags">
                        {% for tag in posts.tags.all %}
                        <a>{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Single Post Section End -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Kelly</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>
  <script src={% static "assets/vendor/waypoints/noframework.waypoints.js" %}></script>
  <script src={% static "assets/vendor/php-email-form/validate.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

</main>
</body>

</html>

templates/blog/posts_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Portfolio - Kelly Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Kelly - v4.8.1
  * Template URL: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">

     <h1 class="logo me-auto me-lg-0"><a href= {% url 'main_page:main_page_view' %} >Kelly</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a href={% url 'main_page:main_page_view' %}>Home</a></li>
          <li><a href="{% url 'about:about_view' %}">About</a></li>
          <li><a href="resume.html">Resume</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a class="active"  href="{% url 'blog:post_list_view' %}">Blog</a></li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <div class="header-social-links">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
      </div>

    </div>

  </header><!-- End Header -->


  <!-- Categories Section Begin -->
    <section class="categories categories-grid spad">
        <div class="categories__post">
            <div class="container">
                <div class="categories__grid__post">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            {% for item in posts_list %}
                            <div class="categories__list__post__item">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="categories__post__item__pic small__item">
                                            <img src="{{ item.photo.url }}" class="categories__post__item__pic small__item" alt="">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="categories__post__item__text">
                                            <h3><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></h3>
                                            <p>{{ item.text| safe | truncatechars:250 }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="categories__pagination">
                                        <a href="#">1</a>
                                        <a href="#">2</a>
                                        <a href="#">3</a>
                                        <a href="#">Next</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Categories Section End -->

   <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Kelly</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>
  <script src={% static "assets/vendor/waypoints/noframework.waypoints.js" %}></script>
  <script src={% static "assets/vendor/php-email-form/validate.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

</main>
</body>

</html>

templates/contact/contact.html
       <!-- Portfolio item 1 modal popup-->
        <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="assets/img/close-icon.svg" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">Project Name</h2>
                                    <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                    <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/1.jpg" alt="..." />
                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Client:</strong>
                                            Threads
                                        </li>
                                        <li>
                                            <strong>Category:</strong>
                                            Illustration
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="fas fa-xmark me-1"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

templates/main_page/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Kelly Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">

      <h1 class="logo me-auto me-lg-0"><a href={% url 'main_page:main_page_view' %}>Kelly</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="active" href={% url 'main_page:main_page_view' %}>Home</a></li>
          <li><a href="{% url 'about:about_view' %}">About</a></li>
          <li><a href="resume.html">Resume</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a href="{% url 'blog:post_list_view' %}">Blog</a></li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
{% for item in main_page %}
      <div class="header-social-links">
        <a href="{{ item.facebook }}" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="{{ item.instagram }}" class="instagram"><i class="bi bi-instagram"></i></a>
      </div>

    </div>

  </header><!-- End Header -->
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center" >
    <img src="{{ item.photo.url }}" class="img-fluid    ">
    <div class="container d-flex flex-column align-items-center" data-aos="zoom-in" data-aos-delay="100">
        <h1>{{ item.title}}</h1>
        <h2>{{ item.desc }}</h2>
        <a href="{% url 'about:about_view' %}" class="btn-about">About Me</a>
    </div>
  </section><!-- End Hero -->
{% endfor %}
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Kelly</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>
  <script src={% static "assets/vendor/waypoints/noframework.waypoints.js" %}></script>
  <script src={% static "assets/vendor/php-email-form/validate.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

</body>

</html>